config:

  # Just some info stuff; not used by the patching scripts
  name: u-boot-rockchip64
  kind: u-boot
  type: vendor # or: vendor
  branch: u-boot-v2022.07
  last-known-good-tag: v2022.07

  # .dts files in these directories will be copied as-is to the build tree; later ones overwrite earlier ones.
  # This is meant to provide a way to "add a board DTS" without having to null-patch them in.
  dts-directories:
    - { source: "dt", target: "arch/arm/dts" }


