name: Build Armbian  
  
on:  
  workflow_dispatch:  
    inputs:  
      BOARD:  
        description: 'Board type'  
        required: true 
        default: 'tpm312'
        type: choice
        options:
          - tpm312
      BRANCH:  
        description: 'Armbian branch'  
        default: 'current'  
        required: false 
        type: choice 
        options:
          - current
          - edge
      RELEASE:  
        description: 'Release name' 
        default: 'bookworm'
        required: true  
        type: choice
        options:
          - jammy
          - noble
          - bullseye
          - bookworm
      BUILD_MINIMAL:  
        description: 'Build minimal system'  
        default: 'no'  
        required: false  
        type: choice
        options:
          - no
          - yes
      BUILD_DESKTOP:  
        description: 'Build desktop environment'  
        default: 'no'  
        required: false  
        type: choice
        options:
          - no
          - yes
      KERNEL_CONFIGURE:  
        description: 'Configure kernel'  
        default: 'no'  
        required: false  
        type: choice 
        options:
          - no
      COMPRESS_OUTPUTIMAGE:  
        description: 'Compress output image'  
        default: 'sha,xz'  
        required: false  
        type: string  
      BOOT_LOGO:  
        description: 'Include boot logo'  
        default: 'no'  
        required: false  
        type: choice 
        options:
          - no
          - yes
  
jobs:  
  build-armbian:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@v3    
        with:  
          path: ${GITHUB_WORKSPACE}/Armbian-Actions
        
      - name: Download source code
        run: |
          df -hT ${PWD}
          git clone -q --single-branch --depth=1 --branch=main https://github.com/armbian/build.git build 
          git clone -q --single-branch --depth=1 --branch=main https://github.com/Lemon1151/Armbian-Actions.git Armbian-Actions
          ln -sf ${GITHUB_WORKSPACE}/build ${GITHUB_WORKSPACE}/build
          
          # 检查并合并 config 和 userpatches 文件夹    
          cp -rf "${GITHUB_WORKSPACE}/addboard/*" "${GITHUB_WORKSPACE}/build"
  
      - name: Compile Armbian [ ${{ inputs.RELEASE }} ] 
        run: |  
          cd ${GITHUB_WORKSPACE}/build/ 
          ./compile.sh BOARD=${{ inputs.BOARD }} RELEASE=${{ inputs.RELEASE }} BRANCH=${{ inputs.BRANCH }} BUILD_MINIMAL=${{ inputs.BUILD_MINIMAL }} \
                           BUILD_DESKTOP=${{ inputs.BUILD_DESKTOP }} KERNEL_CONFIGURE=${{ inputs.KERNEL_CONFIGURE }} COMPRESS_OUTPUTIMAGE=${{ inputs.COMPRESS_OUTPUTIMAGE }} BOOT_LOGO=${{ inputs.BOOT_LOGO }}
          
      - name: Set current year and month  
        run: |  
          echo "CURRENT_YEAR_MONTH=$(date +'%Y%m')" >> $GITHUB_ENV  
            
      - name: Create Release  
        if: success()  
        uses: ncipollo/release-action@main  
        with:  
          artifacts: "/home/runner/work/main/build/output/images/*"  
          token: ${{ secrets.MY_TOKEN }}  
          tag: "Armbian_${{ github.event.inputs.RELEASE }}_${{ env.CURRENT_YEAR_MONTH }}"  
          name: "Armbian ${{ github.event.inputs.RELEASE }} Build (${{ env.CURRENT_YEAR_MONTH }})"  
          body: "Automated build of Armbian for ${{ github.event.inputs.BOARD }} using ${{ github.event.inputs.RELEASE }}."  
          draft: false  
          prerelease: false  
  
      - name: Cleanup  
        if: success()  
        run: |  
          rm -rf /home/runner/work/main/build/output/images/*
